import {
  Patient,
  Doctor,
  Appointment,
  Invoice,
  WardBed,
  StaffMember,
  PharmacyItem,
  AuditLog,
  SystemCompliance,
  AdvancePayment,
  RefundPayment,
  InsuranceApproval,
  PosTransaction,
  ReceptionToken,
} from './types';
import { getPatientPhoto } from './utils/patientImages';

export const initialDoctors: Doctor[] = [
  {
    id: 'DOC-101',
    name: 'Dr. Sarah Jenkins, MD',
    specialty: 'Cardiology',
    department: 'Cardiovascular Care',
    roomNumber: 'Suite 302',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableHours: '08:00 AM - 04:00 PM',
    consultationFee: 250,
    status: 'Available',
  },
  {
    id: 'DOC-102',
    name: 'Dr. Marcus Vance, MD, FACS',
    specialty: 'Orthopedic Surgery',
    department: 'Surgical Sciences',
    roomNumber: 'OR 4 / Suite 210',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Wed', 'Fri'],
    availableHours: '09:00 AM - 05:00 PM',
    consultationFee: 280,
    status: 'In Surgery',
  },
  {
    id: 'DOC-103',
    name: 'Dr. Elena Rostova, MD',
    specialty: 'Neurology',
    department: 'Neurosciences',
    roomNumber: 'Suite 415',
    avatar: 'https://images.unsplash.com/photo-1594824813589-fb5ff5b3f2f8?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Tue', 'Thu', 'Sat'],
    availableHours: '08:30 AM - 03:30 PM',
    consultationFee: 260,
    status: 'In Consultation',
  },
  {
    id: 'DOC-104',
    name: 'Dr. Julian Thorne, MD',
    specialty: 'Emergency Medicine',
    department: 'Trauma & Emergency',
    roomNumber: 'ER Triage 1',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    availableHours: '24/7 Shift Rotation',
    consultationFee: 320,
    status: 'Available',
  },
  {
    id: 'DOC-105',
    name: 'Dr. Anita Patel, MD',
    specialty: 'Pediatrics',
    department: 'Pediatric Care',
    roomNumber: 'Suite 108',
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableHours: '09:00 AM - 04:30 PM',
    consultationFee: 210,
    status: 'Available',
  },
  {
    id: 'DOC-106',
    name: 'Dr. David Chen, MD',
    specialty: 'Internal Medicine',
    department: 'General Medicine',
    roomNumber: 'Suite 102',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    availableHours: '08:00 AM - 04:30 PM',
    consultationFee: 220,
    status: 'Available',
  },
  {
    id: 'DOC-107',
    name: 'Dr. Maya Lin, MD',
    specialty: 'Medical Oncology',
    department: 'Oncology & Infusion',
    roomNumber: 'Suite 501',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    availableHours: '09:00 AM - 04:00 PM',
    consultationFee: 310,
    status: 'Available',
  },
  {
    id: 'DOC-108',
    name: 'Dr. Robert Taylor, MD',
    specialty: 'Pulmonology',
    department: 'Pulmonary & Respiratory',
    roomNumber: 'Suite 318',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
    availableDays: ['Mon', 'Wed', 'Thu', 'Fri'],
    availableHours: '08:30 AM - 04:30 PM',
    consultationFee: 270,
    status: 'Available',
  },
];

export const initialPatients: Patient[] = [
  {
    id: 'PT-10492',
    avatar: getPatientPhoto('PT-10492', 'Eleanor Pemberton', 'Female'),
    firstName: 'Eleanor',
    lastName: 'Pemberton',
    age: 58,
    gender: 'Female',
    dob: '1968-03-14',
    bloodGroup: 'A+',
    phone: '+1 (555) 234-8901',
    email: 'eleanor.p@example.com',
    address: '742 Evergreen Terrace, Springfield, IL',
    emergencyContact: {
      name: 'David Pemberton',
      relationship: 'Spouse',
      phone: '+1 (555) 234-8902',
    },
    status: 'Inpatient',
    wardOrRoom: 'Cardiology Unit - Bed 304',
    primaryPhysicianId: 'DOC-101',
    primaryPhysicianName: 'Dr. Sarah Jenkins, MD',
    allergies: [
      { allergen: 'Penicillin', severity: 'Severe' },
      { allergen: 'Sulfa Drugs', severity: 'Moderate' },
    ],
    chronicConditions: ['Hypertension', 'Type 2 Diabetes', 'Coronary Artery Disease'],
    vitals: [
      {
        heartRate: 76,
        bloodPressureSys: 132,
        bloodPressureDia: 84,
        spO2: 98,
        temperature: 98.6,
        respiratoryRate: 16,
        recordedAt: '2026-09-02T18:30:00Z',
      },
      {
        heartRate: 82,
        bloodPressureSys: 138,
        bloodPressureDia: 88,
        spO2: 97,
        temperature: 99.1,
        respiratoryRate: 18,
        recordedAt: '2026-09-02T10:15:00Z',
      },
    ],
    medications: [
      {
        id: 'MED-01',
        name: 'Atorvastatin',
        dosage: '40 mg',
        frequency: 'Once daily at bedtime',
        route: 'Oral',
        prescribedBy: 'Dr. Sarah Jenkins',
        startDate: '2026-08-15',
        status: 'Active',
      },
      {
        id: 'MED-02',
        name: 'Metformin HCl',
        dosage: '850 mg',
        frequency: 'Twice daily with meals',
        route: 'Oral',
        prescribedBy: 'Dr. Sarah Jenkins',
        startDate: '2026-05-10',
        status: 'Active',
      },
      {
        id: 'MED-03',
        name: 'Lisinopril',
        dosage: '10 mg',
        frequency: 'Once daily mornings',
        route: 'Oral',
        prescribedBy: 'Dr. Sarah Jenkins',
        startDate: '2026-08-15',
        status: 'Active',
      },
    ],
    labResults: [
      {
        id: 'LAB-901',
        testName: 'Lipid Panel - Total Cholesterol',
        category: 'Biochemistry',
        department: 'Laboratory',
        cptCode: 'CPT 80061',
        orderedDate: '2026-08-28',
        resultDate: '2026-08-29',
        status: 'Elevated',
        value: '228 mg/dL',
        referenceRange: '< 200 mg/dL',
        orderedBy: 'Dr. Sarah Jenkins',
        findings: 'Total cholesterol 228 mg/dL, Triglycerides 175 mg/dL, HDL 42 mg/dL, LDL calculated 151 mg/dL.',
        impression: 'Primary mixed hyperlipidemia with elevated atherogenic particle burden.',
        technicianOrRadiologist: 'Alex Mercer, MLS(ASCP)',
        sentToPatient: true,
        sentToDoctor: true,
        sentDate: '2026-08-29 11:30 AM',
        notes: 'Advised lifestyle modification alongside statin therapy',
      },
      {
        id: 'LAB-902',
        testName: '12-Lead Electrocardiogram (ECG)',
        category: 'Cardiology',
        department: 'Cardiology / Procedures',
        cptCode: 'CPT 93000',
        orderedDate: '2026-09-01',
        resultDate: '2026-09-01',
        status: 'Normal',
        value: 'Sinus Rhythm at 74 bpm, No ST elevation',
        referenceRange: 'Normal Sinus Rhythm',
        orderedBy: 'Dr. Sarah Jenkins',
        findings: 'Normal axis, PR interval 158 ms, QRS duration 86 ms, QTc 418 ms. No pathological Q waves or acute ST-T wave abnormalities.',
        impression: 'Normal 12-lead electrocardiogram. No ischemic changes.',
        technicianOrRadiologist: 'Marcus Reed, CCT',
        sentToPatient: true,
        sentToDoctor: true,
        sentDate: '2026-09-01 10:15 AM',
      },
      {
        id: 'LAB-903',
        testName: 'Hemoglobin A1c (HbA1c)',
        category: 'Hematology',
        department: 'Laboratory',
        cptCode: 'CPT 83036',
        orderedDate: '2026-08-28',
        resultDate: '2026-08-29',
        status: 'Elevated',
        value: '7.2%',
        referenceRange: '< 5.7%',
        orderedBy: 'Dr. Sarah Jenkins',
        findings: 'HbA1c measured at 7.2% via high-performance liquid chromatography.',
        impression: 'Sub-optimally controlled Type 2 Diabetes Mellitus.',
        technicianOrRadiologist: 'Alex Mercer, MLS(ASCP)',
        sentToPatient: true,
        sentToDoctor: true,
        sentDate: '2026-08-29 11:32 AM',
      },
      {
        id: 'RAD-904',
        testName: 'Chest X-Ray PA & Lateral View',
        category: 'Radiology',
        department: 'Radiology & Imaging',
        modality: 'Digital Radiography',
        cptCode: 'CPT 71046',
        orderedDate: '2026-09-02',
        resultDate: '2026-09-02',
        status: 'Normal',
        value: 'Clear lung parenchyma, cardiac silhouette within normal limits',
        referenceRange: 'Normal cardiothoracic anatomy',
        orderedBy: 'Dr. Sarah Jenkins',
        findings: 'No focal pulmonary consolidation, pleural effusion, or pneumothorax identified. Mediastinal contours are unremarkable. Cardiothoracic ratio 0.48.',
        impression: 'No acute cardiopulmonary disease. Lungs are clear.',
        technicianOrRadiologist: 'Dr. Katherine Cole, MD (Radiologist)',
        sentToPatient: true,
        sentToDoctor: true,
        sentDate: '2026-09-02 02:45 PM',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-1',
        date: '2026-09-01',
        doctorName: 'Dr. Sarah Jenkins, MD',
        doctorSpecialty: 'Cardiology',
        chiefComplaint: 'Mild retrosternal chest tightness on moderate exertion.',
        assessment: 'Stable coronary artery disease under medical management. Vitals stabilizing in Ward Bed 304.',
        treatmentPlan: 'Maintain current anti-hypertensive titration, scheduled echo-Doppler tomorrow.',
        diagnosisCode: 'ICD-10 I25.10',
      },
    ],
    insurance: {
      provider: 'Blue Cross Blue Shield',
      policyNumber: 'BCBS-IL-884920',
      groupNumber: 'GRP-9921',
      coveragePercentage: 80,
      copayAmount: 35,
      status: 'Verified',
      expiryDate: '2027-12-31',
    },
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-09-02T18:30:00Z',
  },
  {
    id: 'PT-10493',
    avatar: getPatientPhoto('PT-10493', 'Mateo Rodriguez', 'Male'),
    firstName: 'Mateo',
    lastName: 'Rodriguez',
    age: 34,
    gender: 'Male',
    dob: '1992-07-22',
    bloodGroup: 'O+',
    phone: '+1 (555) 438-1920',
    email: 'm.rodriguez@example.com',
    address: '148 Oakridge Boulevard, Chicago, IL',
    emergencyContact: {
      name: 'Sofia Rodriguez',
      relationship: 'Sister',
      phone: '+1 (555) 438-1924',
    },
    status: 'Outpatient',
    wardOrRoom: undefined,
    primaryPhysicianId: 'DOC-102',
    primaryPhysicianName: 'Dr. Marcus Vance, MD, FACS',
    allergies: [],
    chronicConditions: ['Asthma (Mild intermittent)'],
    vitals: [
      {
        heartRate: 68,
        bloodPressureSys: 118,
        bloodPressureDia: 76,
        spO2: 99,
        temperature: 98.4,
        respiratoryRate: 14,
        recordedAt: '2026-09-02T14:00:00Z',
      },
    ],
    medications: [
      {
        id: 'MED-04',
        name: 'Albuterol Inhaler',
        dosage: '90 mcg/actuation',
        frequency: '1-2 puffs PRN wheezing',
        route: 'Inhalation',
        prescribedBy: 'Dr. Marcus Vance',
        startDate: '2026-01-10',
        status: 'Active',
      },
      {
        id: 'MED-05',
        name: 'Ibuprofen',
        dosage: '400 mg',
        frequency: 'Every 8 hours with food for knee pain',
        route: 'Oral',
        prescribedBy: 'Dr. Marcus Vance',
        startDate: '2026-08-25',
        status: 'Active',
      },
    ],
    labResults: [
      {
        id: 'LAB-904',
        testName: 'Right Knee MRI Arthrogram',
        category: 'Radiology',
        orderedDate: '2026-08-26',
        resultDate: '2026-08-27',
        status: 'Normal',
        value: 'Intact ACL/PCL; grade 1 medial meniscus fraying without tear',
        referenceRange: 'Standard imaging protocol',
        orderedBy: 'Dr. Marcus Vance',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-2',
        date: '2026-08-27',
        doctorName: 'Dr. Marcus Vance, MD, FACS',
        doctorSpecialty: 'Orthopedic Surgery',
        chiefComplaint: 'Right knee lateral discomfort post-marathon training.',
        assessment: 'Patellofemoral syndrome; MRI clears major ligament disruption.',
        treatmentPlan: 'Physical therapy referral for quad strengthening; avoid heavy squats.',
        diagnosisCode: 'ICD-10 M22.2X1',
      },
    ],
    insurance: {
      provider: 'UnitedHealthcare Choice Plus',
      policyNumber: 'UHC-99214710',
      groupNumber: 'CORP-481',
      coveragePercentage: 85,
      copayAmount: 25,
      status: 'Verified',
      expiryDate: '2027-06-30',
    },
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-02T14:00:00Z',
  },
  {
    id: 'PT-10494',
    avatar: getPatientPhoto('PT-10494', 'Amara Okonkwo', 'Female'),
    firstName: 'Amara',
    lastName: 'Okonkwo',
    age: 42,
    gender: 'Female',
    dob: '1984-11-03',
    bloodGroup: 'B+',
    phone: '+1 (555) 781-4432',
    email: 'amara.o@example.com',
    address: '900 North Michigan Ave, Chicago, IL',
    emergencyContact: {
      name: 'Chinedu Okonkwo',
      relationship: 'Brother',
      phone: '+1 (555) 781-4435',
    },
    status: 'Emergency',
    wardOrRoom: 'ER Triage Bay 2',
    primaryPhysicianId: 'DOC-104',
    primaryPhysicianName: 'Dr. Julian Thorne, MD',
    allergies: [
      { allergen: 'Latex', severity: 'Moderate' },
      { allergen: 'Codeine', severity: 'Severe' },
    ],
    chronicConditions: ['Migraine with aura'],
    vitals: [
      {
        heartRate: 104,
        bloodPressureSys: 154,
        bloodPressureDia: 96,
        spO2: 96,
        temperature: 101.4,
        respiratoryRate: 22,
        recordedAt: '2026-09-02T21:45:00Z',
      },
    ],
    medications: [
      {
        id: 'MED-06',
        name: 'Sumatriptan Succinate',
        dosage: '50 mg',
        frequency: 'PRN acute migraine onset',
        route: 'Oral',
        prescribedBy: 'Dr. Elena Rostova',
        startDate: '2025-11-12',
        status: 'Active',
      },
    ],
    labResults: [
      {
        id: 'LAB-905',
        testName: 'Emergency Complete Blood Count (CBC) with Diff',
        category: 'Hematology',
        orderedDate: '2026-09-02',
        status: 'Pending',
        value: 'Processing in Central Lab',
        referenceRange: 'WBC 4.5-11.0 x10^3/uL',
        orderedBy: 'Dr. Julian Thorne',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-3',
        date: '2026-09-02',
        doctorName: 'Dr. Julian Thorne, MD',
        doctorSpecialty: 'Emergency Medicine',
        chiefComplaint: 'Acute right lower quadrant abdominal pain with fever.',
        assessment: 'Possible acute appendicitis vs mesenteric adenitis. Fasting initiated.',
        treatmentPlan: 'IV access secured, stat abdomen/pelvis contrast CT scan ordered.',
        diagnosisCode: 'ICD-10 R10.31',
      },
    ],
    insurance: {
      provider: 'Aetna Health HMO',
      policyNumber: 'AET-4431980',
      groupNumber: 'IL-5510',
      coveragePercentage: 90,
      copayAmount: 50,
      status: 'Verified',
      expiryDate: '2027-01-15',
    },
    createdAt: '2026-09-02T21:30:00Z',
    updatedAt: '2026-09-02T22:00:00Z',
  },
  {
    id: 'PT-10495',
    avatar: getPatientPhoto('PT-10495', 'Harrison Brooks', 'Male'),
    firstName: 'Harrison',
    lastName: 'Brooks',
    age: 71,
    gender: 'Male',
    dob: '1955-06-19',
    bloodGroup: 'AB-',
    phone: '+1 (555) 902-8321',
    email: 'h.brooks@example.com',
    address: '320 Shoreline Drive, Evanston, IL',
    emergencyContact: {
      name: 'Clara Brooks',
      relationship: 'Daughter',
      phone: '+1 (555) 902-8329',
    },
    status: 'Inpatient',
    wardOrRoom: 'ICU Bed 02',
    primaryPhysicianId: 'DOC-103',
    primaryPhysicianName: 'Dr. Elena Rostova, MD',
    allergies: [
      { allergen: 'Aspirin', severity: 'Severe' },
    ],
    chronicConditions: ['Transient Ischemic Attack (TIA) History', 'Atrial Fibrillation'],
    vitals: [
      {
        heartRate: 88,
        bloodPressureSys: 144,
        bloodPressureDia: 92,
        spO2: 95,
        temperature: 98.8,
        respiratoryRate: 17,
        recordedAt: '2026-09-02T20:00:00Z',
      },
    ],
    medications: [
      {
        id: 'MED-07',
        name: 'Apixaban (Eliquis)',
        dosage: '5 mg',
        frequency: 'Twice daily',
        route: 'Oral',
        prescribedBy: 'Dr. Elena Rostova',
        startDate: '2026-08-01',
        status: 'Active',
      },
    ],
    labResults: [
      {
        id: 'LAB-906',
        testName: 'Brain MRI with Diffusion Weighting (DWI)',
        category: 'Radiology',
        orderedDate: '2026-09-01',
        resultDate: '2026-09-01',
        status: 'Normal',
        value: 'No acute ischemic penumbra identified. Stable white matter changes.',
        referenceRange: 'Normal intracranial study',
        orderedBy: 'Dr. Elena Rostova',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-4',
        date: '2026-09-01',
        doctorName: 'Dr. Elena Rostova, MD',
        doctorSpecialty: 'Neurology',
        chiefComplaint: 'Episodes of transient speech hesitancy lasting 4 minutes.',
        assessment: 'TIA ruled stable under continuous telemetry in ICU monitoring.',
        treatmentPlan: 'Continuous telemetry; speech pathology assessment scheduled.',
        diagnosisCode: 'ICD-10 G45.9',
      },
    ],
    insurance: {
      provider: 'Medicare Part A & B + Cigna Supplemental',
      policyNumber: 'MEDICARE-48821',
      groupNumber: 'CIG-SUP-11',
      coveragePercentage: 95,
      copayAmount: 15,
      status: 'Verified',
      expiryDate: '2028-12-31',
    },
    createdAt: '2026-08-30T14:20:00Z',
    updatedAt: '2026-09-02T20:00:00Z',
  },
  {
    id: 'PT-10496',
    avatar: getPatientPhoto('PT-10496', 'Chloe Kim', 'Female'),
    firstName: 'Chloe',
    lastName: 'Kim',
    age: 7,
    gender: 'Female',
    dob: '2019-04-12',
    bloodGroup: 'O-',
    phone: '+1 (555) 612-9981',
    email: 'family.kim@example.com',
    address: '511 Maple Court, Naperville, IL',
    emergencyContact: {
      name: 'Grace Kim',
      relationship: 'Mother',
      phone: '+1 (555) 612-9981',
    },
    status: 'Outpatient',
    wardOrRoom: undefined,
    primaryPhysicianId: 'DOC-105',
    primaryPhysicianName: 'Dr. Anita Patel, MD',
    allergies: [
      { allergen: 'Peanuts', severity: 'Severe' },
    ],
    chronicConditions: ['Atopic Dermatitis'],
    vitals: [
      {
        heartRate: 92,
        bloodPressureSys: 98,
        bloodPressureDia: 64,
        spO2: 100,
        temperature: 98.6,
        respiratoryRate: 20,
        recordedAt: '2026-09-02T16:00:00Z',
      },
    ],
    medications: [
      {
        id: 'MED-08',
        name: 'Hydrocortisone 1% Cream',
        dosage: 'Thin layer twice daily',
        frequency: 'Topical as needed for flare-ups',
        route: 'Topical',
        prescribedBy: 'Dr. Anita Patel',
        startDate: '2026-07-15',
        status: 'Active',
      },
    ],
    labResults: [
      {
        id: 'LAB-907',
        testName: 'Pediatric Comprehensive IgE Food Allergen Panel',
        category: 'Pathology',
        orderedDate: '2026-09-02',
        resultDate: '2026-09-03',
        status: 'Elevated',
        value: 'Peanut IgE: 14.8 kU/L (Class III High)',
        referenceRange: '< 0.35 kU/L (Negative)',
        orderedBy: 'Dr. Anita Patel, MD',
        notes: 'Confirms persistent severe peanut hypersensitivity. Anaphylaxis action plan updated.',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-5',
        date: '2026-09-02',
        doctorName: 'Dr. Anita Patel, MD',
        doctorSpecialty: 'Pediatrics',
        chiefComplaint: 'Annual developmental wellness checkup and school immunization verification.',
        assessment: 'Healthy development, height/weight in 75th percentile.',
        treatmentPlan: 'Administered annual influenza vaccine booster; EpiPen 0.15mg renewed.',
        diagnosisCode: 'ICD-10 Z00.129',
      },
    ],
    insurance: {
      provider: 'Cigna Global Health',
      policyNumber: 'CIG-9004123',
      groupNumber: 'TECH-77',
      coveragePercentage: 90,
      copayAmount: 20,
      status: 'Verified',
      expiryDate: '2027-08-31',
    },
    createdAt: '2026-07-10T10:00:00Z',
    updatedAt: '2026-09-02T16:30:00Z',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'APT-2026-001',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    patientAge: 58,
    patientGender: 'Female',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiovascular Care',
    roomNumber: 'Suite 302',
    date: '2026-09-03',
    timeSlot: '09:00 AM',
    type: 'Specialist Review',
    status: 'In Consultation',
    priority: 'Urgent',
    reason: 'Post-admission cardiac telemetry review and echocardiogram review.',
    queueNumber: 1,
    estimatedWaitMinutes: 0,
    notes: 'Patient escorted from Room 304',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'APT-2026-002',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    patientAge: 34,
    patientGender: 'Male',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Marcus Vance, MD, FACS',
    department: 'Surgical Sciences',
    roomNumber: 'Suite 210',
    date: '2026-09-03',
    timeSlot: '09:45 AM',
    type: 'Follow-up',
    status: 'Checked-In',
    priority: 'Normal',
    reason: 'Knee MRI results evaluation and physical therapy progress check.',
    queueNumber: 2,
    estimatedWaitMinutes: 15,
    notes: 'Arrived at reception, vitals completed',
    createdAt: '2026-08-28T14:00:00Z',
  },
  {
    id: 'APT-2026-003',
    patientId: 'PT-10494',
    patientName: 'Amara Okonkwo',
    patientAge: 42,
    patientGender: 'Female',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Julian Thorne, MD',
    department: 'Trauma & Emergency',
    roomNumber: 'ER Triage 1',
    date: '2026-09-03',
    timeSlot: '10:15 AM',
    type: 'Emergency Triage',
    status: 'Scheduled',
    priority: 'Emergency',
    reason: 'Acute RLQ abdominal pain; surgery consult standby.',
    queueNumber: 3,
    estimatedWaitMinutes: 30,
    notes: 'Fasting protocol active',
    createdAt: '2026-09-02T21:40:00Z',
  },
  {
    id: 'APT-2026-004',
    patientId: 'PT-10496',
    patientName: 'Chloe Kim',
    patientAge: 7,
    patientGender: 'Female',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Anita Patel, MD',
    department: 'Pediatric Care',
    roomNumber: 'Suite 108',
    date: '2026-09-03',
    timeSlot: '11:00 AM',
    type: 'General Consultation',
    status: 'Scheduled',
    priority: 'Normal',
    reason: 'Routine seasonal allergy management and pulmonary spirometry test.',
    queueNumber: 4,
    estimatedWaitMinutes: 45,
    createdAt: '2026-08-29T11:30:00Z',
  },
  {
    id: 'APT-2026-005',
    patientId: 'PT-10495',
    patientName: 'Harrison Brooks',
    patientAge: 71,
    patientGender: 'Male',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Elena Rostova, MD',
    department: 'Neurosciences',
    roomNumber: 'Suite 415',
    date: '2026-09-03',
    timeSlot: '01:30 PM',
    type: 'Specialist Review',
    status: 'Scheduled',
    priority: 'Urgent',
    reason: 'Neurological cognitive assessment following bedside TIA stabilization.',
    queueNumber: 5,
    estimatedWaitMinutes: 120,
    createdAt: '2026-09-01T16:00:00Z',
  },
  {
    id: 'APT-2026-006',
    patientId: 'PT-10493',
    patientName: 'Sofia Rodriguez',
    patientAge: 34,
    patientGender: 'Female',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiovascular Care',
    roomNumber: 'Virtual Room 1',
    date: '2026-09-03',
    timeSlot: '02:00 PM',
    type: 'Telehealth Consultation',
    status: 'Checked-In',
    priority: 'Urgent',
    reason: 'Remote hypertensive titration, ambulatory BP log evaluation, and chest tightness follow-up.',
    queueNumber: 6,
    estimatedWaitMinutes: 5,
    notes: 'Patient confirmed in virtual lobby. Camera and mic verified via iOS WebRTC.',
    createdAt: '2026-09-02T18:00:00Z',
    isTelehealth: true,
    telehealthDetails: {
      platform: 'WebRTC Clinical Room',
      roomId: 'TH-CARDIO-8821',
      meetingLink: 'https://telehealth.medcore.health/room/TH-CARDIO-8821',
      patientStatus: 'Waiting in Room',
      patientJoinedAt: '2026-09-03T13:54:00Z',
      deviceInfo: 'Apple iPad Pro (iOS 19.1) · Safari WebRTC',
      connectionQuality: 'Excellent (HD 1080p)',
      telehealthConsentSigned: true,
    },
  },
  {
    id: 'APT-2026-007',
    patientId: 'PT-10492',
    patientName: 'David Pemberton',
    patientAge: 58,
    patientGender: 'Male',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Anita Patel, MD',
    department: 'Pediatric & Family Medicine',
    roomNumber: 'Virtual Room 2',
    date: '2026-09-03',
    timeSlot: '02:45 PM',
    type: 'Telehealth Consultation',
    status: 'Scheduled',
    priority: 'Normal',
    reason: 'Routine quarterly glycemic control and lipid panel trend consultation.',
    queueNumber: 7,
    estimatedWaitMinutes: 35,
    notes: 'Pre-consult questionnaire received. Blood glucose averages sent via portal.',
    createdAt: '2026-09-01T09:15:00Z',
    isTelehealth: true,
    telehealthDetails: {
      platform: 'HIPAA Video Bridge',
      roomId: 'TH-FAM-4109',
      meetingLink: 'https://telehealth.medcore.health/room/TH-FAM-4109',
      patientStatus: 'Scheduled / Not Joined',
      deviceInfo: 'Windows 11 PC · Chrome 138',
      connectionQuality: 'Good (720p)',
      telehealthConsentSigned: true,
    },
  },
  {
    id: 'APT-2026-008',
    patientId: 'PT-10495',
    patientName: 'Clara Brooks',
    patientAge: 62,
    patientGender: 'Female',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Marcus Vance, MD, FACS',
    department: 'Surgical Sciences',
    roomNumber: 'Virtual Room 3',
    date: '2026-09-03',
    timeSlot: '03:30 PM',
    type: 'Remote Follow-up',
    status: 'Scheduled',
    priority: 'Normal',
    reason: 'Post-operative laparoscopic incision visual inspection and range-of-motion assessment.',
    queueNumber: 8,
    estimatedWaitMinutes: 75,
    notes: 'Incision photos pre-uploaded to chart. No fever reported.',
    createdAt: '2026-09-02T11:20:00Z',
    isTelehealth: true,
    telehealthDetails: {
      platform: 'WebRTC Clinical Room',
      roomId: 'TH-SURG-9032',
      meetingLink: 'https://telehealth.medcore.health/room/TH-SURG-9032',
      patientStatus: 'Scheduled / Not Joined',
      deviceInfo: 'Android 16 · Chrome Mobile',
      connectionQuality: 'Good (720p)',
      telehealthConsentSigned: true,
    },
  },
  {
    id: 'APT-2026-009',
    patientId: 'PT-10494',
    patientName: 'Chinedu Okonkwo',
    patientAge: 45,
    patientGender: 'Male',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Elena Rostova, MD',
    department: 'Neurosciences',
    roomNumber: 'Virtual Room 4',
    date: '2026-09-03',
    timeSlot: '10:00 AM',
    type: 'Telehealth Consultation',
    status: 'Completed',
    priority: 'Normal',
    reason: 'Migraine aura frequency review & response to abortive sumatriptan therapy.',
    queueNumber: 9,
    estimatedWaitMinutes: 0,
    notes: 'Telehealth visit completed. Refill sent to outpatient pharmacy.',
    createdAt: '2026-09-01T08:00:00Z',
    isTelehealth: true,
    telehealthDetails: {
      platform: 'WebRTC Clinical Room',
      roomId: 'TH-NEURO-1120',
      meetingLink: 'https://telehealth.medcore.health/room/TH-NEURO-1120',
      patientStatus: 'Completed',
      patientJoinedAt: '2026-09-03T09:58:00Z',
      deviceInfo: 'macOS Sonoma · Safari WebRTC',
      connectionQuality: 'Excellent (HD 1080p)',
      telehealthConsentSigned: true,
    },
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'INV-2026-0081',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    patientPhone: '+1 (555) 234-8901',
    patientEmail: 'eleanor.p@example.com',
    appointmentId: 'APT-2026-001',
    issueDate: '2026-09-01',
    invoiceTime: '10:15:30 AM',
    createdAt: '2026-09-01T10:15:30Z',
    dueDate: '2026-09-30',
    items: [
      {
        id: 'ITEM-1',
        description: 'Comprehensive Inpatient Cardiology Care (Per Diem)',
        category: 'Room & Nursing',
        unitCost: 850.0,
        quantity: 2,
        amount: 1700.0,
      },
      {
        id: 'ITEM-2',
        description: '12-Lead Electrocardiogram & Telemetry Analysis',
        category: 'Cardiology',
        unitCost: 320.0,
        quantity: 1,
        amount: 320.0,
      },
      {
        id: 'ITEM-3',
        description: 'Lipid Panel & Complete Metabolic Blood Assay',
        category: 'Lab Test',
        unitCost: 190.0,
        quantity: 1,
        amount: 190.0,
      },
      {
        id: 'ITEM-4',
        description: 'Specialist Physician Rounding (Dr. Jenkins)',
        category: 'Consultation',
        unitCost: 250.0,
        quantity: 2,
        amount: 500.0,
      },
    ],
    subtotal: 2710.0,
    tax: 0.0,
    totalAmount: 2710.0,
    insuranceCoveredAmount: 2168.0,
    insuranceCovered: 2168.0,
    copayAmount: 35.0,
    patientPayable: 542.0,
    amountPaid: 0.0,
    balanceDue: 542.0,
    status: 'Pending',
    transactions: [],
    notes: 'Primary insurer Blue Cross Blue Shield pre-authorized claim #BCBS-CLAIM-9941',
    insuranceClaimNumber: 'BCBS-CLAIM-9941',
  },
  {
    id: 'INV-2026-0080',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    patientPhone: '+1 (555) 438-1920',
    patientEmail: 'm.rodriguez@example.com',
    appointmentId: 'APT-2026-002',
    issueDate: '2026-08-27',
    invoiceTime: '03:20:10 PM',
    createdAt: '2026-08-27T15:20:10Z',
    dueDate: '2026-09-27',
    items: [
      {
        id: 'ITEM-5',
        description: 'Orthopedic Specialty Consultation (Dr. Vance)',
        category: 'Consultation',
        unitCost: 280.0,
        quantity: 1,
        amount: 280.0,
      },
      {
        id: 'ITEM-6',
        description: 'High-Resolution 3T MRI Right Knee with Contrast',
        category: 'Radiology',
        unitCost: 1200.0,
        quantity: 1,
        amount: 1200.0,
      },
      {
        id: 'ITEM-7',
        description: 'Orthopedic Knee Stabilizer Brace (Medical Grade)',
        category: 'Pharmacy',
        unitCost: 95.0,
        quantity: 1,
        amount: 95.0,
      },
    ],
    subtotal: 1575.0,
    tax: 0.0,
    totalAmount: 1575.0,
    insuranceCoveredAmount: 1338.75,
    insuranceCovered: 1338.75,
    copayAmount: 25.0,
    patientPayable: 236.25,
    amountPaid: 236.25,
    balanceDue: 0.0,
    status: 'Paid',
    paymentMethod: 'Credit/Debit Card',
    transactions: [
      {
        transactionId: 'TXN-SEC-93108',
        timestamp: '2026-08-27T15:24:10Z',
        amountPaid: 236.25,
        method: 'Credit/Debit Card',
        cardLast4: '4242',
        authCode: 'AUTH-992147-OK',
        gatewayStatus: 'Success',
      },
    ],
    notes: 'Settled in full via secure hospital payment gateway with Apple Pay token',
    insuranceClaimNumber: 'UHC-CLAIM-1209',
  },
  {
    id: 'INV-2026-0079',
    patientId: 'PT-10496',
    patientName: 'Chloe Kim',
    patientPhone: '+1 (555) 612-9981',
    patientEmail: 'family.kim@example.com',
    issueDate: '2026-09-02',
    invoiceTime: '04:15:00 PM',
    createdAt: '2026-09-02T16:15:00Z',
    dueDate: '2026-10-02',
    items: [
      {
        id: 'ITEM-8',
        description: 'Pediatric Annual Preventive Health Exam',
        category: 'Consultation',
        unitCost: 210.0,
        quantity: 1,
        amount: 210.0,
      },
      {
        id: 'ITEM-9',
        description: 'Influenza Quadrivalent Pediatric Vaccine & Administration',
        category: 'Pharmacy',
        unitCost: 65.0,
        quantity: 1,
        amount: 65.0,
      },
    ],
    subtotal: 275.0,
    tax: 0.0,
    totalAmount: 275.0,
    insuranceCoveredAmount: 247.5,
    insuranceCovered: 247.5,
    copayAmount: 20.0,
    patientPayable: 27.5,
    amountPaid: 27.5,
    balanceDue: 0.0,
    status: 'Paid',
    paymentMethod: 'HSA/FSA',
    transactions: [
      {
        transactionId: 'TXN-HSA-88310',
        timestamp: '2026-09-02T16:35:00Z',
        amountPaid: 27.5,
        method: 'HSA/FSA',
        cardLast4: '7190',
        authCode: 'HSA-CLAIM-PASS',
        gatewayStatus: 'Success',
      },
    ],
    notes: 'Eligible medical expense cleared via Cigna HSA card',
    insuranceClaimNumber: 'CIG-CLM-7890',
  },
];

export const initialWardBeds: WardBed[] = [
  {
    id: 'BED-101',
    wardName: 'ICU Wing (Critical Care)',
    bedNumber: 'ICU-01',
    status: 'Available',
  },
  {
    id: 'BED-102',
    wardName: 'ICU Wing (Critical Care)',
    bedNumber: 'ICU-02',
    status: 'Occupied',
    patientId: 'PT-10495',
    patientName: 'Harrison Brooks',
    assignedDoctor: 'Dr. Elena Rostova',
    admissionDate: '2026-08-30',
  },
  {
    id: 'BED-103',
    wardName: 'Cardiology Unit (Level 3)',
    bedNumber: 'Bed 304',
    status: 'Occupied',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    assignedDoctor: 'Dr. Sarah Jenkins',
    admissionDate: '2026-08-31',
  },
  {
    id: 'BED-104',
    wardName: 'Cardiology Unit (Level 3)',
    bedNumber: 'Bed 305',
    status: 'Available',
  },
  {
    id: 'BED-105',
    wardName: 'Emergency Triage & Observation',
    bedNumber: 'ER-Bay-01',
    status: 'Available',
  },
  {
    id: 'BED-106',
    wardName: 'Emergency Triage & Observation',
    bedNumber: 'ER-Bay-02',
    status: 'Occupied',
    patientId: 'PT-10494',
    patientName: 'Amara Okonkwo',
    assignedDoctor: 'Dr. Julian Thorne',
    admissionDate: '2026-09-02',
  },
  {
    id: 'BED-107',
    wardName: 'Pediatric Wing',
    bedNumber: 'Peds-101',
    status: 'Available',
  },
  {
    id: 'BED-108',
    wardName: 'General Surgery Recovery',
    bedNumber: 'PostOp-201',
    status: 'Maintenance',
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'STF-01',
    name: 'Dr. Julian Thorne, MD',
    role: 'doctor',
    department: 'Trauma & Emergency',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-3001',
    email: 'j.thorne@apexhealth.org',
    roomOrStation: 'ER Station 1',
    licenseNumber: 'MD-IL-78921',
    status: 'On Duty',
  },
  {
    id: 'STF-02',
    name: 'Dr. Sarah Jenkins, MD',
    role: 'doctor',
    department: 'Cardiovascular Care',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-3002',
    email: 's.jenkins@apexhealth.org',
    roomOrStation: 'Suite 302',
    licenseNumber: 'MD-IL-44120',
    status: 'In Consultation',
  },
  {
    id: 'STF-03',
    name: 'Nurse Jacqueline Chen, RN, BSN',
    role: 'nurse',
    department: 'Intensive Care Unit (ICU)',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-4010',
    email: 'j.chen@apexhealth.org',
    roomOrStation: 'ICU Central Nursing Bay',
    licenseNumber: 'RN-IL-89231',
    status: 'On Duty',
  },
  {
    id: 'STF-04',
    name: 'Nurse David Morales, RN',
    role: 'nurse',
    department: 'Emergency & Triage',
    shift: 'Evening (15:00 - 23:00)',
    phone: '+1 (555) 912-4015',
    email: 'd.morales@apexhealth.org',
    roomOrStation: 'Triage Desk B',
    licenseNumber: 'RN-IL-90112',
    status: 'On Duty',
  },
  {
    id: 'STF-05',
    name: 'Dr. Tariq Al-Mansoor, PharmD',
    role: 'pharmacist',
    department: 'Central Pharmacy & Dispensing',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-5001',
    email: 't.almansoor@apexhealth.org',
    roomOrStation: 'Ground Floor Pharmacy Counter',
    licenseNumber: 'RPH-IL-66321',
    status: 'On Duty',
  },
  {
    id: 'STF-06',
    name: 'Chloe Bennett',
    role: 'receptionist',
    department: 'Patient Admissions & Scheduling',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-6002',
    email: 'c.bennett@apexhealth.org',
    roomOrStation: 'Main Atrium Desk 1',
    licenseNumber: 'ADM-REC-104',
    status: 'On Duty',
  },
  {
    id: 'STF-07',
    name: 'Administrator Robert Stirling, MBA',
    role: 'admin',
    department: 'Hospital Administration & Compliance',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-1001',
    email: 'r.stirling@apexhealth.org',
    roomOrStation: 'Executive Suite 501',
    licenseNumber: 'FACHE-9921',
    status: 'On Duty',
  },
  {
    id: 'STF-08',
    name: 'Morgan Ellis, RHIT',
    role: 'medical-coder',
    department: 'Medical Coding & Insurance Review',
    shift: 'Morning (07:00 - 15:00)',
    phone: '+1 (555) 912-8001',
    email: 'm.ellis@apexhealth.org',
    roomOrStation: 'Revenue Integrity Desk',
    licenseNumber: 'RHIT-482019',
    status: 'On Duty',
  },
];

export const initialPharmacy: PharmacyItem[] = [
  {
    id: 'PHARM-01',
    sku: 'MED-ATOR-40',
    name: 'Atorvastatin Calcium',
    genericName: 'Lipitor',
    category: 'Cardiovascular',
    dosageForm: 'Tablet',
    stockQuantity: 420,
    minThreshold: 100,
    unitPrice: 1.45,
    batchNumber: 'BAT-2026-081',
    expiryDate: '2027-11-30',
    storageCondition: 'Room Temp (20-25 C)',
    manufacturer: 'Pfizer Pharmaceuticals',
  },
  {
    id: 'PHARM-02',
    sku: 'MED-METF-850',
    name: 'Metformin Hydrochloride 850mg',
    genericName: 'Glucophage',
    category: 'Endocrine',
    dosageForm: 'Tablet',
    stockQuantity: 28,
    minThreshold: 75,
    unitPrice: 0.85,
    batchNumber: 'BAT-2026-104',
    expiryDate: '2027-08-15',
    storageCondition: 'Room Temp (20-25 C)',
    manufacturer: 'Bristol-Myers Squibb',
  },
  {
    id: 'PHARM-03',
    sku: 'MED-AMOX-500',
    name: 'Amoxicillin Trihydrate 500mg',
    genericName: 'Amoxil',
    category: 'Antibiotics',
    dosageForm: 'Capsule',
    stockQuantity: 310,
    minThreshold: 80,
    unitPrice: 1.20,
    batchNumber: 'BAT-2026-199',
    expiryDate: '2028-02-28',
    storageCondition: 'Room Temp (20-25 C)',
    manufacturer: 'GlaxoSmithKline',
  },
  {
    id: 'PHARM-04',
    sku: 'MED-ALB-INHAL',
    name: 'Albuterol Sulfate Inhalation Aerosol',
    genericName: 'ProAir HFA',
    category: 'Respiratory',
    dosageForm: 'Inhaler',
    stockQuantity: 64,
    minThreshold: 30,
    unitPrice: 28.50,
    batchNumber: 'BAT-2026-302',
    expiryDate: '2027-04-30',
    storageCondition: 'Room Temp (20-25 C)',
    manufacturer: 'Teva Respiratory',
  },
  {
    id: 'PHARM-05',
    sku: 'MED-APIX-5',
    name: 'Apixaban 5mg',
    genericName: 'Eliquis',
    category: 'Cardiovascular',
    dosageForm: 'Tablet',
    stockQuantity: 18,
    minThreshold: 50,
    unitPrice: 8.90,
    batchNumber: 'BAT-2026-411',
    expiryDate: '2027-09-30',
    storageCondition: 'Room Temp (20-25 C)',
    manufacturer: 'Bristol-Myers Squibb',
  },
  {
    id: 'PHARM-06',
    sku: 'MED-FENT-IV',
    name: 'Fentanyl Citrate IV 50mcg/mL (2mL Ampule)',
    genericName: 'Sublimaze',
    category: 'Emergency IV',
    dosageForm: 'Injection IV',
    stockQuantity: 45,
    minThreshold: 20,
    unitPrice: 14.75,
    batchNumber: 'BAT-VAULT-99',
    expiryDate: '2027-06-30',
    storageCondition: 'Controlled Substance Vault',
    manufacturer: 'Hospira / Pfizer',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'LOG-9941',
    timestamp: '2026-09-02T22:45:10Z',
    userName: 'Dr. Julian Thorne, MD',
    userRole: 'doctor',
    action: 'CREATE',
    resourceType: 'Patient Record',
    resourceId: 'PT-10494',
    details: 'Emergency triage admission protocol initiated for Amara Okonkwo.',
    ipAddress: '10.240.12.84',
    complianceFlag: 'HIPAA Access Log',
  },
  {
    id: 'LOG-9940',
    timestamp: '2026-09-02T21:50:30Z',
    userName: 'Chloe Bennett',
    userRole: 'receptionist',
    action: 'UPDATE',
    resourceType: 'Appointment',
    resourceId: 'APT-2026-002',
    details: 'Checked-in Mateo Rodriguez for 09:45 AM orthopedic consultation.',
    ipAddress: '10.240.12.102',
    complianceFlag: 'HIPAA Access Log',
  },
  {
    id: 'LOG-9939',
    timestamp: '2026-09-02T20:15:12Z',
    userName: 'Administrator Robert Stirling',
    userRole: 'admin',
    action: 'CLAIM_EXPORT',
    resourceType: 'Billing Invoice',
    resourceId: 'INV-2026-0080',
    details: 'PCI-DSS Tokenized transaction settled $236.25 via Apple Pay token.',
    ipAddress: '10.240.12.15',
    complianceFlag: 'PCI-DSS Payment Log',
  },
  {
    id: 'LOG-9938',
    timestamp: '2026-09-02T19:30:00Z',
    userName: 'Dr. Tariq Al-Mansoor',
    userRole: 'pharmacist',
    action: 'DISPENSE',
    resourceType: 'Prescription',
    resourceId: 'MED-01',
    details: 'Dispensed Atorvastatin 40mg (30 day supply) to Inpatient Bed 304.',
    ipAddress: '10.240.12.44',
    complianceFlag: 'HIPAA Access Log',
  },
];

export const initialCompliance: SystemCompliance = {
  hipaaAuditLogEnabled: true,
  aes256EncryptionAtRest: true,
  hl7FhirInteropEnabled: true,
  roleBasedAccessActive: true,
  gdprConsentTracking: true,
  offlineSyncCache: true,
  sessionTimeoutMinutes: 15,
  backupFrequencyHours: 4,
};

export const initialAdvancePayments: AdvancePayment[] = [
  {
    id: 'ADV-2026-001',
    receiptNumber: 'RCP-ADV-8841',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    patientMrn: 'PT-10492',
    amount: 1500.0,
    paymentMethod: 'Credit/Debit Card',
    date: '2026-09-02',
    time: '09:30 AM',
    purpose: 'Inpatient Bed Admission',
    remainingBalance: 1100.0,
    status: 'Partially Utilized',
    cashierName: 'Chloe Bennett (Reception Desk A)',
    terminalId: 'POS-TERM-01 (Verifone)',
    notes: 'Pre-admission security retainer deposit for Cardiology Bed 304.',
  },
  {
    id: 'ADV-2026-002',
    receiptNumber: 'RCP-ADV-8842',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    patientMrn: 'PT-10493',
    amount: 800.0,
    paymentMethod: 'Cash',
    date: '2026-09-02',
    time: '11:15 AM',
    purpose: 'OT / Surgical Deposit',
    remainingBalance: 800.0,
    status: 'Active',
    cashierName: 'Chloe Bennett (Reception Desk A)',
    notes: 'Knee arthroscopy surgical package initial deposit.',
  },
  {
    id: 'ADV-2026-003',
    receiptNumber: 'RCP-ADV-8843',
    patientId: 'PT-10494',
    patientName: 'Clara Davis',
    patientMrn: 'PT-10494',
    amount: 500.0,
    paymentMethod: 'Credit/Debit Card',
    date: '2026-09-01',
    time: '02:45 PM',
    purpose: 'OPD Retainer',
    remainingBalance: 0.0,
    status: 'Utilized',
    cashierName: 'Marcus Cole (Reception Desk B)',
    terminalId: 'POS-TERM-02 (Ingenico)',
    notes: 'Neurology diagnostic workup retainer, adjusted against INV-2026-0079.',
  },
];

export const initialRefundPayments: RefundPayment[] = [
  {
    id: 'REF-2026-001',
    voucherNumber: 'RFND-VOUCH-102',
    patientId: 'PT-10494',
    patientName: 'Clara Davis',
    originalReferenceType: 'Service Cancellation',
    originalReferenceId: 'INV-2026-0079',
    amount: 120.0,
    refundMethod: 'Cash',
    reason: 'Procedure Cancelled',
    date: '2026-09-02',
    time: '04:10 PM',
    authorizedBy: 'Robert Stirling (Finance Lead)',
    cashierName: 'Chloe Bennett (Reception Desk A)',
    status: 'Completed',
    notes: 'Elective EEG cancellation requested 24h prior, refund disbursed in cash from POS drawer.',
  },
];

export const initialInsuranceApprovals: InsuranceApproval[] = [
  {
    id: 'APP-2026-001',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    patientMrn: 'PT-10492',
    insuranceProvider: 'Blue Cross Blue Shield',
    policyNumber: 'BCBS-9021-X',
    approvalNumber: 'AUTH-BCBS-882910',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiovascular Care',
    serviceCategory: 'Procedure',
    serviceName: 'Coronary Angiography & 2D Echo Doppler',
    serviceCode: 'CPT-93306',
    estimatedCost: 2400.0,
    approvedAmount: 2160.0,
    copayPercentage: 10,
    copayAmount: 240.0,
    approvalStatus: 'Approved',
    approvalDate: '2026-09-02',
    validUntil: '2026-09-16',
    authorisedBy: 'Dr. Arthur Vance (Medical Director)',
    remarks: 'Pre-auth cleared under emergency cardiac pathway. Inpatient copay fixed at 10%.',
  },
  {
    id: 'APP-2026-002',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    patientMrn: 'PT-10493',
    insuranceProvider: 'Aetna Health Choice',
    policyNumber: 'AET-4491-M',
    approvalNumber: 'AUTH-AET-551940',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Marcus Vance, MD, FACS',
    department: 'Surgical Sciences',
    serviceCategory: 'Radiology',
    serviceName: 'MRI Right Knee with Contrast & 3D Reconstruction',
    serviceCode: 'CPT-73721',
    estimatedCost: 1100.0,
    approvedAmount: 990.0,
    copayPercentage: 10,
    copayAmount: 110.0,
    approvalStatus: 'Approved',
    approvalDate: '2026-09-02',
    validUntil: '2026-09-30',
    authorisedBy: 'Chloe Bennett (Billing Pre-Auth)',
    remarks: 'Approved with clinical notes attached.',
  },
  {
    id: 'APP-2026-003',
    patientId: 'PT-10494',
    patientName: 'Clara Davis',
    patientMrn: 'PT-10494',
    insuranceProvider: 'UnitedHealthcare',
    policyNumber: 'UHC-8109-D',
    approvalNumber: 'AUTH-UHC-109283',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Elena Rostova, MD',
    department: 'Neurosciences',
    serviceCategory: 'Lab Test',
    serviceName: 'Comprehensive Neurological Autoantibody Panel',
    serviceCode: 'CPT-86255',
    estimatedCost: 650.0,
    approvedAmount: 520.0,
    copayPercentage: 20,
    copayAmount: 130.0,
    approvalStatus: 'Approved',
    approvalDate: '2026-09-01',
    validUntil: '2026-09-15',
    authorisedBy: 'Chloe Bennett (Billing Pre-Auth)',
    remarks: 'Tier-2 diagnostic panel authorization.',
  },
];

export const initialPosTransactions: PosTransaction[] = [
  {
    id: 'POS-TX-2026-0091',
    terminalId: 'POS-TERM-01',
    terminalName: 'Desk A - Verifone V200c',
    batchNumber: 'BATCH-4092',
    invoiceId: 'INV-2026-0080',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    cardType: 'Visa',
    cardLast4: '4242',
    authCode: 'APPR-88192',
    rrnNumber: 'RRN-99281726351',
    amount: 236.25,
    status: 'Approved & Settled',
    transactionDate: '2026-09-02',
    transactionTime: '10:15 AM',
    cashierName: 'Chloe Bennett',
  },
  {
    id: 'POS-TX-2026-0092',
    terminalId: 'POS-TERM-01',
    terminalName: 'Desk A - Verifone V200c',
    batchNumber: 'BATCH-4092',
    advanceId: 'ADV-2026-001',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    cardType: 'MasterCard',
    cardLast4: '5512',
    authCode: 'APPR-33821',
    rrnNumber: 'RRN-99281726352',
    amount: 1500.0,
    status: 'Approved & Settled',
    transactionDate: '2026-09-02',
    transactionTime: '09:30 AM',
    cashierName: 'Chloe Bennett',
  },
  {
    id: 'POS-TX-2026-0093',
    terminalId: 'POS-TERM-02',
    terminalName: 'Desk B - Ingenico Move5000',
    batchNumber: 'BATCH-4092',
    patientId: 'PT-10494',
    patientName: 'Clara Davis',
    cardType: 'Apple Pay',
    cardLast4: '9012',
    authCode: 'APPR-77192',
    rrnNumber: 'RRN-99281726353',
    amount: 500.0,
    status: 'Approved & Settled',
    transactionDate: '2026-09-01',
    transactionTime: '02:45 PM',
    cashierName: 'Marcus Cole',
  },
  {
    id: 'POS-TX-2026-0094',
    terminalId: 'POS-TERM-01',
    terminalName: 'Desk A - Verifone V200c',
    batchNumber: 'BATCH-4092',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    cardType: 'Cash / POS Drawer',
    authCode: 'CASH-REC-1092',
    rrnNumber: 'CSH-00192',
    amount: 800.0,
    status: 'Approved & Settled',
    transactionDate: '2026-09-02',
    transactionTime: '11:15 AM',
    cashierName: 'Chloe Bennett',
  },
];

export const initialReceptionTokens: ReceptionToken[] = [
  {
    id: 'TOK-101',
    tokenNumber: 'T-101',
    patientId: 'PT-10492',
    patientName: 'Eleanor Pemberton',
    patientPhone: '+1 (555) 234-8901',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiovascular Care',
    serviceType: 'Consultation',
    priority: 'Urgent',
    status: 'In Consultation',
    createdTime: '08:15 AM',
    estimatedWaitMins: 0,
    calledAt: '08:30 AM',
    counterOrRoom: 'Suite 302',
    currentStage: '3_DOCTOR_EMR',
    paymentScheme: {
      schemeType: 'Insurance',
      insuranceProvider: 'Blue Cross Blue Shield',
      policyNumber: 'BCBS-99418274',
      network: 'Comprehensive PPO Tier 1',
      coveragePercent: 80,
      copayAmount: 25,
      preAuthStatus: 'Approved',
    },
    vitals: {
      bpSystolic: 138,
      bpDiastolic: 88,
      heartRate: 78,
      spO2: 97,
      temperature: 98.6,
      respiratoryRate: 16,
      bloodGlucose: 110,
      painScale: 2,
      triageLevel: 'Level 3 - Urgent',
      nursingNotes: 'Mild chest tightness on exertion, ambulatory, alerts checked.',
      nurseName: 'Nurse Jessica Adams, RN',
      recordedAt: '08:22 AM',
    },
    doctorOrders: {
      healthSummary: 'Patient presents with mild retrosternal chest tightness on exertion for 3 days. History of essential hypertension and hyperlipidemia. Cardiovascular exam reveals regular S1/S2 without murmurs.',
      chiefComplaint: 'Subacute exertional chest tightness and shortness of breath',
      clinicalAssessment: 'Likely exertional angina or hypertensive cardiovascular stress. Requires cardiac enzymes, lipid panel, and resting 12-lead ECG.',
      diagnoses: [
        { code: 'I20.9', description: 'Angina pectoris, unspecified' },
        { code: 'I10', description: 'Essential (primary) hypertension' },
      ],
      consultationFee: 250,
      labRequests: [
        { id: 'LAB-ORD-101', testName: 'Cardiac Troponin I & CK-MB', category: 'Biochemistry', price: 95, status: 'Ordered' },
        { id: 'LAB-ORD-102', testName: 'Lipid Profile Comprehensive', category: 'Biochemistry', price: 65, status: 'Ordered' },
      ],
      radiologyRequests: [
        { id: 'RAD-ORD-101', studyName: 'Chest X-Ray PA View', modality: 'Digital Radiography', price: 110, status: 'Ordered' },
      ],
      procedureRequests: [
        { id: 'PRC-ORD-101', cptCode: 'CPT 93000', procedureName: '12-Lead Electrocardiogram (ECG) with interpretation', price: 95, status: 'Scheduled' },
        { id: 'PRC-ORD-102', cptCode: 'CPT 99214', procedureName: 'Office Outpatient Visit Level 4', price: 250, status: 'Completed' },
      ],
      orderedByDoctorId: 'DOC-101',
      orderedByDoctorName: 'Dr. Sarah Jenkins, MD',
      orderedAt: '08:45 AM',
    },
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '08:15 AM', action: 'Patient checked in with Blue Cross Insurance', actor: 'Reception Desk' },
      { stage: '2_NURSING_VITALS', timestamp: '08:22 AM', action: 'Vitals & Triage Level 3 logged', actor: 'Nurse Jessica Adams' },
      { stage: '3_DOCTOR_EMR', timestamp: '08:30 AM', action: 'Doctor consultation initiated, diagnoses & orders entered', actor: 'Dr. Sarah Jenkins' },
    ],
  },
  {
    id: 'TOK-102',
    tokenNumber: 'T-102',
    patientId: 'PT-10493',
    patientName: 'Mateo Rodriguez',
    patientPhone: '+1 (555) 345-6789',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Marcus Vance, MD, FACS',
    department: 'Surgical Sciences',
    serviceType: 'Consultation',
    priority: 'Normal',
    status: 'Waiting',
    createdTime: '08:35 AM',
    estimatedWaitMins: 10,
    counterOrRoom: 'Triage Room 2',
    currentStage: '2_NURSING_VITALS',
    paymentScheme: {
      schemeType: 'Discount Card',
      discountCardName: 'Senior Citizen Card (20%)',
      discountCardNumber: 'SNR-2026-8891',
      discountPercent: 20,
    },
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '08:35 AM', action: 'Token created with Senior Citizen Discount Card (20%)', actor: 'Reception Desk' },
      { stage: '2_NURSING_VITALS', timestamp: '08:37 AM', action: 'Patient queued at Nursing Station for baseline vitals', actor: 'Triage Queue' },
    ],
  },
  {
    id: 'TOK-103',
    tokenNumber: 'T-103',
    patientId: 'PT-10494',
    patientName: 'Clara Davis',
    patientPhone: '+1 (555) 456-7890',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Elena Rostova, MD',
    department: 'Neurosciences',
    serviceType: 'Consultation',
    priority: 'Normal',
    status: 'Waiting',
    createdTime: '08:45 AM',
    estimatedWaitMins: 15,
    counterOrRoom: 'Counter 1',
    currentStage: '1_REGISTRATION',
    paymentScheme: {
      schemeType: 'Self-Pay',
      notes: 'Patient opted for direct cash / card settlement',
    },
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '08:45 AM', action: 'Intake initiated under Self-Pay scheme', actor: 'Reception Desk' },
    ],
  },
  {
    id: 'TOK-104',
    tokenNumber: 'T-104',
    patientId: 'PT-10495',
    patientName: 'Liam Cooper',
    patientPhone: '+1 (555) 567-8901',
    doctorId: 'DOC-106',
    doctorName: 'Dr. David Chen, MD',
    department: 'General Medicine',
    serviceType: 'Billing & Cashier',
    priority: 'Normal',
    status: 'Waiting',
    createdTime: '09:00 AM',
    estimatedWaitMins: 5,
    counterOrRoom: 'Cashier Counter 2',
    currentStage: '4_CASHIER_BILLING',
    paymentScheme: {
      schemeType: 'Self-Pay',
      notes: 'Self-Pay Cashier queue',
    },
    vitals: {
      bpSystolic: 122,
      bpDiastolic: 78,
      heartRate: 72,
      spO2: 99,
      temperature: 98.4,
      respiratoryRate: 15,
      triageLevel: 'Level 4 - Less Urgent',
      nurseName: 'Nurse Mark Wilson, RN',
      recordedAt: '08:40 AM',
    },
    doctorOrders: {
      healthSummary: 'Patient presents with persistent abdominal bloating and mild epigastric discomfort for 2 weeks.',
      chiefComplaint: 'Epigastric discomfort and dyspepsia',
      clinicalAssessment: 'Functional dyspepsia vs H. pylori gastritis. Ordered metabolic panel, CBC, and complete abdominal ultrasound.',
      diagnoses: [{ code: 'K30', description: 'Functional dyspepsia' }],
      consultationFee: 150,
      labRequests: [
        { id: 'LAB-ORD-1', testName: 'Comprehensive Metabolic Panel (CMP)', category: 'Biochemistry', price: 65, status: 'Ordered' },
        { id: 'LAB-ORD-2', testName: 'Complete Blood Count (CBC)', category: 'Hematology', price: 45, status: 'Ordered' },
      ],
      radiologyRequests: [
        { id: 'RAD-ORD-1', studyName: 'Ultrasound Abdomen Complete', modality: 'Ultrasound', price: 180, status: 'Ordered' },
      ],
      procedureRequests: [
        { id: 'PRC-ORD-1', cptCode: 'CPT 99214', procedureName: 'Office Consultation Level 4', price: 150, status: 'Completed' },
      ],
      orderedByDoctorId: 'DOC-106',
      orderedByDoctorName: 'Dr. David Chen, MD',
      orderedAt: '09:10 AM',
    },
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '08:30 AM', action: 'Token issued under Self-Pay', actor: 'Reception Desk' },
      { stage: '2_NURSING_VITALS', timestamp: '08:40 AM', action: 'Vitals documented: BP 122/78, HR 72', actor: 'Nurse Mark Wilson' },
      { stage: '3_DOCTOR_EMR', timestamp: '09:10 AM', action: 'Doctor consultation completed. Lab & Ultrasound orders submitted', actor: 'Dr. David Chen' },
      { stage: '4_CASHIER_BILLING', timestamp: '09:12 AM', action: 'Transferred to Cashier for invoicing ($440 total)', actor: 'EMR Dispatch' },
    ],
  },
  {
    id: 'TOK-105',
    tokenNumber: 'T-105',
    patientId: 'PT-10496',
    patientName: 'Sophia Martinez',
    patientPhone: '+1 (555) 678-9012',
    doctorId: 'DOC-108',
    doctorName: 'Dr. Robert Taylor, MD',
    department: 'Pulmonary & Respiratory',
    serviceType: 'Consultation',
    priority: 'Normal',
    status: 'Completed',
    createdTime: '07:45 AM',
    estimatedWaitMins: 0,
    calledAt: '08:00 AM',
    completedAt: '08:50 AM',
    counterOrRoom: 'Phlebotomy & Imaging',
    currentStage: '6_COMPLETED_REPORTS',
    paymentScheme: {
      schemeType: 'Insurance',
      insuranceProvider: 'Aetna Health HMO',
      policyNumber: 'AET-8829104',
      network: 'Premier Care Network',
      coveragePercent: 80,
      copayAmount: 30,
      preAuthStatus: 'Approved',
    },
    vitals: {
      bpSystolic: 118,
      bpDiastolic: 76,
      heartRate: 70,
      spO2: 99,
      temperature: 98.6,
      respiratoryRate: 14,
      triageLevel: 'Level 4 - Less Urgent',
      nurseName: 'Nurse Jessica Adams, RN',
      recordedAt: '07:50 AM',
    },
    doctorOrders: {
      healthSummary: 'Routine respiratory follow-up and evaluation of mild dry cough after viral illness.',
      chiefComplaint: 'Lingering post-viral dry cough',
      clinicalAssessment: 'Post-infectious bronchial hyperreactivity. Lung fields clear on auscultation.',
      diagnoses: [{ code: 'J06.9', description: 'Acute upper respiratory infection, unspecified' }],
      consultationFee: 180,
      labRequests: [
        { id: 'LAB-ORD-3', testName: 'Complete Blood Count (CBC)', category: 'Hematology', price: 45, status: 'Completed' },
      ],
      radiologyRequests: [
        { id: 'RAD-ORD-2', studyName: 'Chest X-Ray PA & Lateral View', modality: 'Digital Radiography', price: 120, status: 'Completed' },
      ],
      procedureRequests: [
        { id: 'PRC-ORD-2', cptCode: 'CPT 94640', procedureName: 'Pressurized Inhalation Nebulization', price: 65, status: 'Completed' },
      ],
      orderedByDoctorId: 'DOC-108',
      orderedByDoctorName: 'Dr. Robert Taylor, MD',
      orderedAt: '08:05 AM',
    },
    billingSummary: {
      invoiceNumber: 'INV-2026-9041',
      subtotal: 410,
      schemeType: 'Insurance',
      insuranceCoveredAmount: 328,
      discountAmount: 0,
      copayOrSelfPayAmount: 82,
      totalPaid: 82,
      balanceDue: 0,
      paymentMethod: 'Credit/Debit Card',
      paymentStatus: 'Paid',
      receiptNumber: 'RCP-89214',
      cashierName: 'Cashier David Miller',
      billedAt: '08:15 AM',
    },
    diagnosticReports: [
      {
        id: 'REP-101',
        testOrStudyName: 'Complete Blood Count (CBC with Differential)',
        department: 'Laboratory',
        category: 'Hematology',
        cptOrCode: 'CPT 85025',
        date: '2026-09-10',
        time: '08:35 AM',
        findings: 'WBC: 6.8 K/uL, RBC: 4.65 M/uL, Hemoglobin: 14.1 g/dL, Hematocrit: 42.0%, Platelets: 260 K/uL. Differential shows normal segmented neutrophils (62%) and lymphocytes (28%).',
        impression: 'All hematological parameters within expected physiological reference ranges. No leukocytosis or anemia.',
        resultValue: 'WBC 6.8 | Hb 14.1 | Plt 260',
        referenceRange: 'Hb: 12.0 - 15.5 g/dL, WBC: 4.0 - 11.0 K/uL',
        status: 'Normal',
        technicianOrRadiologist: 'Alex Mercer, MLS(ASCP)',
        completedAt: '08:35 AM',
        sentToPatient: true,
        sentToDoctor: true,
        sentTimestamp: '2026-09-10 08:36 AM',
      },
      {
        id: 'REP-102',
        testOrStudyName: 'Chest X-Ray (PA & Lateral View)',
        department: 'Radiology',
        category: 'Radiology & Imaging',
        cptOrCode: 'CPT 71046',
        date: '2026-09-10',
        time: '08:45 AM',
        findings: 'Lungs are clear bilaterally without focal consolidation, pneumothorax, or pleural effusion. Cardiomediastinal silhouette is normal in size and contour. Osseous structures intact.',
        impression: 'No acute cardiopulmonary disease. Clear lung fields. Normal examination.',
        resultValue: 'Clear, no acute infiltrate',
        referenceRange: 'Normal radiologic anatomy',
        status: 'Normal',
        technicianOrRadiologist: 'Dr. Katherine Cole, MD (Radiology)',
        completedAt: '08:45 AM',
        sentToPatient: true,
        sentToDoctor: true,
        sentTimestamp: '2026-09-10 08:46 AM',
      },
    ],
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '07:45 AM', action: 'Token registered with Aetna Health Insurance', actor: 'Reception Desk' },
      { stage: '2_NURSING_VITALS', timestamp: '07:50 AM', action: 'Vitals documented: BP 118/76, SpO2 99%', actor: 'Nurse Jessica Adams' },
      { stage: '3_DOCTOR_EMR', timestamp: '08:05 AM', action: 'Doctor consultation completed. CBC & Chest X-Ray ordered', actor: 'Dr. Robert Taylor' },
      { stage: '4_CASHIER_BILLING', timestamp: '08:15 AM', action: 'Cashier settled copay of $82 via Card. Service token cleared for Diagnostics', actor: 'Cashier David Miller' },
      { stage: '5_DIAGNOSTICS_PROCEDURES', timestamp: '08:45 AM', action: 'CBC & Chest X-Ray completed and signed off', actor: 'Lab & Radiology Suites' },
      { stage: '6_COMPLETED_REPORTS', timestamp: '08:50 AM', action: 'Reports dispatched to patient portal & doctor EMR. Visible date & department wise', actor: 'Clinical Diagnostic Core' },
    ],
  },
  {
    id: 'TOK-106',
    tokenNumber: 'T-106',
    patientId: 'PT-10497',
    patientName: 'James Wilson',
    patientPhone: '+1 (555) 789-0123',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Elena Rostova, MD',
    department: 'Trauma & Emergency',
    serviceType: 'Insurance Authorisation',
    priority: 'VIP / Elderly',
    status: 'In Consultation',
    createdTime: '08:50 AM',
    estimatedWaitMins: 0,
    calledAt: '09:05 AM',
    counterOrRoom: 'Radiology Suite 1',
    currentStage: '5_DIAGNOSTICS_PROCEDURES',
    paymentScheme: {
      schemeType: 'Discount Card',
      discountCardName: 'Hospital Employee Staff Card (30%)',
      discountCardNumber: 'EMP-CARD-4421',
      discountPercent: 30,
    },
    vitals: {
      bpSystolic: 130,
      bpDiastolic: 84,
      heartRate: 76,
      spO2: 98,
      temperature: 98.7,
      respiratoryRate: 16,
      triageLevel: 'Level 3 - Urgent',
      nurseName: 'Nurse Jessica Adams, RN',
      recordedAt: '08:52 AM',
    },
    doctorOrders: {
      healthSummary: 'Headache following minor slip, alert and oriented x3, neurologic exam non-focal. Cranial nerves intact.',
      chiefComplaint: 'Post-fall headache and mild cervical tenderness',
      clinicalAssessment: 'Rule out acute intracranial hemorrhage or cervical spine strain.',
      diagnoses: [{ code: 'R51.9', description: 'Headache, unspecified' }],
      consultationFee: 200,
      labRequests: [],
      radiologyRequests: [
        { id: 'RAD-ORD-3', studyName: 'CT Brain / Head Non-Contrast', modality: 'Computed Tomography (CT)', price: 350, status: 'In Progress' },
      ],
      procedureRequests: [
        { id: 'PRC-ORD-3', cptCode: 'CPT 93000', procedureName: '12-Lead Electrocardiogram ECG', price: 95, status: 'Scheduled' },
      ],
      orderedByDoctorId: 'DOC-103',
      orderedByDoctorName: 'Dr. Elena Rostova, MD',
      orderedAt: '09:05 AM',
    },
    billingSummary: {
      invoiceNumber: 'INV-2026-9042',
      subtotal: 645,
      schemeType: 'Discount Card',
      insuranceCoveredAmount: 0,
      discountAmount: 193.5,
      copayOrSelfPayAmount: 451.5,
      totalPaid: 451.5,
      balanceDue: 0,
      paymentMethod: 'Credit/Debit Card',
      paymentStatus: 'Paid',
      receiptNumber: 'RCP-89215',
      cashierName: 'Cashier David Miller',
      billedAt: '09:15 AM',
    },
    historyLogs: [
      { stage: '1_REGISTRATION', timestamp: '08:50 AM', action: 'Token issued with Staff Discount Card (30%)', actor: 'Reception Desk' },
      { stage: '2_NURSING_VITALS', timestamp: '08:52 AM', action: 'Vitals logged: BP 130/84, HR 76, Triage Level 3', actor: 'Nurse Jessica Adams' },
      { stage: '3_DOCTOR_EMR', timestamp: '09:05 AM', action: 'Dr. Rostova ordered CT Brain & ECG', actor: 'Dr. Elena Rostova' },
      { stage: '4_CASHIER_BILLING', timestamp: '09:15 AM', action: 'Cashier processed invoice with 30% discount. Paid $451.50', actor: 'Cashier David Miller' },
      { stage: '5_DIAGNOSTICS_PROCEDURES', timestamp: '09:18 AM', action: 'Patient dispatched to CT Scanner & ECG Suite', actor: 'Radiology Team' },
    ],
  },
  {
    id: 'TOK-107',
    tokenNumber: 'T-107',
    patientId: 'PT-10498',
    patientName: 'Aria Montgomery',
    patientPhone: '+1 (555) 890-1234',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Anita Patel, MD',
    department: 'Pediatric Care',
    serviceType: 'Consultation',
    priority: 'Normal',
    status: 'Cancelled',
    createdTime: '08:20 AM',
    estimatedWaitMins: 0,
    counterOrRoom: 'Suite 108',
    currentStage: '1_REGISTRATION',
    paymentScheme: {
      schemeType: 'Self-Pay',
    },
  },
];
